spring:
  application:
    name: controle-escalas
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#server:
#  port: 8082
  flyway:
    baseline-on-migrate: true


---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    hibernate:
      ddl-auto: none
  jpa:
    show-sql: false


---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/roster}
    driver-class-name: org.postgresql.Driver
    password:  ${DATASOURCE_PASSWORD:postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    hibernate:
      ddl-auto: none
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

#logging:
#  level:
#    root: "trace"